import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import os
from dotenv import load_dotenv
from pathlib import Path

load_dotenv()

SMTP_SERVER = os.getenv("SMTP_SERVER")
SMTP_PORT = int(os.getenv("SMTP_PORT"))

FROM_EMAIL = os.getenv("FROM_EMAIL")
TO_EMAIL = os.getenv("TO_EMAIL")

SMTP_PASSWORD = os.getenv("SMTP_PASSWORD")

if not SMTP_PASSWORD:
    raise ValueError("Missing SMTP_PASSWORD in .env")


if not FROM_EMAIL or not TO_EMAIL:
    raise ValueError("Missing FROM_EMAIL or TO_EMAIL in .env")

def build_html(frame: dict) -> str:
    rows = ""

    for key, value in frame.items():
        rows += f"""
        <tr>
            <td style="padding:6px;border:1px solid #ddd;"><b>{key}</b></td>
            <td style="padding:6px;border:1px solid #ddd;">{value}</td>
        </tr>
        """

    html = f"""
    <html>
        <body style="font-family:Arial,sans-serif;">
            <h2 style="color:#2c3e50;">LLDP Frame Report</h2>

            <table style="border-collapse:collapse;width:100%;">
                <thead>
                    <tr>
                        <th style="text-align:left;border:1px solid #ddd;padding:6px;">Field</th>
                        <th style="text-align:left;border:1px solid #ddd;padding:6px;">Value</th>
                    </tr>
                </thead>
                <tbody>
                    {rows}
                </tbody>
            </table>

            <p style="margin-top:20px;color:#888;font-size:12px;">
                Generated by LLDP Embedded System
            </p>
        </body>
    </html>
    """

    return html

def send_frame(frame: dict):
    subject = f"LLDP Frame - {frame.get('system_name', 'Unknown')}"

    html = build_html(frame)

    msg = MIMEMultipart("alternative")

    msg["From"] = FROM_EMAIL
    msg["To"] = TO_EMAIL
    msg["Subject"] = subject

    msg.attach(MIMEText(html, "html"))

    with smtplib.SMTP(SMTP_SERVER, SMTP_PORT, timeout=10) as server:
        server.ehlo()
        server.starttls()
        server.ehlo()
        server.login(FROM_EMAIL, SMTP_PASSWORD)

        server.send_message(msg)

